language: vala
sudo: required
dist: trusty
compiler:
 - gcc

install:
# Utils
 - sudo apt-add-repository ppa:vala-team/ppa -y
 - sudo apt-get update -q
 - sudo apt-get install -y checkinstall build-essential libglib2.0-dev libgtk-3-dev libgdk-pixbuf2.0-dev libsoup2.4-dev libjson-glib-dev libnotify-bin python3 valac-0.30 libnotify-dev libopus-dev

before_script:
# ninja
 - git clone git://github.com/martine/ninja.git
 - cd ninja
 - ./bootstrap.py
 - sudo cp ./ninja /usr/bin/ninja
 - cd ..
# meson
 - wget https://github.com/mesonbuild/meson/releases/download/0.26.0/meson_0.26.0.tar.gz
 - tar -xvf meson_0.26.0.tar.gz
 - cd meson-0.26.0
 - sudo python3 install_meson.py --prefix=/usr
 - cd ..
# ffmpeg
 - if [ ! -e "libs" ]; then mkdir libs; fi
 - if [ ! -e "ffmpeg" ]; then mkdir ffmpeg; fi
#
 - cd libs/
 - export PREFIX_DIR="$PWD"
#
 - cd ../ffmpeg
 - wget http://ffmpeg.org/releases/ffmpeg-2.7.2.tar.bz2
 - tar xf ffmpeg*
 - cd ffmpeg*
 - ./configure --prefix="$PREFIX_DIR" --enable-shared --disable-static --disable-programs --disable-protocols --disable-doc --disable-sdl --disable-avfilter --disable-avresample --disable-filters --disable-iconv --disable-network --disable-muxers --disable-postproc --disable-swresample --disable-swscale-alpha --disable-dct --disable-dwt --disable-lsp --disable-lzo --disable-mdct --disable-rdft --disable-fft --disable-faan --disable-vaapi --disable-vdpau --disable-zlib --disable-xlib --disable-bzlib --disable-lzma --disable-encoders --disable-yasm --enable-memalign-hack
 - make -j$(nproc)
 - make install
 - cd ../../
# filter_audio
 - git clone https://github.com/irungentoo/filter_audio
 - cd filter_audio
 - make -j$(nproc)
 - sudo make install
 - cd ..
# libsodium
 - git clone git://github.com/jedisct1/libsodium.git
 - cd libsodium
 - git checkout tags/1.0.3
 - ./autogen.sh
 - ./configure && make -j$(nproc)
 - sudo checkinstall --install --pkgname libsodium --pkgversion 1.0.0 --nodoc -y
 - sudo ldconfig
 - cd ..
# Toxcore
 - git clone https://github.com/irungentoo/toxcore.git
 - cd toxcore
 - autoreconf -if
 - ./configure
 - make -j$(nproc)
 - sudo make install
 - echo '/usr/local/lib/' | sudo tee -a /etc/ld.so.conf.d/locallib.conf
 - sudo ldconfig
 - cd ..

script:
 - mkdir build && cd build
 - meson ..
 - ninja
